apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-ds
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ds
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ds
    spec:
      containers:
        - name: http-echo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: {{ .Values.image.command }}
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: message
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: apiToken
