replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "0.3.0"
  command:
    - "-text=Hello from Helm"

service:
  port: 5678

config:
  message: "Hello from Configmap"

secret:
  apiToken: "secret-token"
